name: Deploy

on:
  push:
    branches:
      - default

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - name: Install
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build module
        run: npm run build
      - name: Build example
        run: npm run --prefix example build
      - name: Publish site
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: example/dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
